---
title: Animeer spritebewegingen met uiterlijken
hero_image: images/banner.png
description: Animeer spritebewegingen zoals lopen of vliegen door tussen specifieke uiterlijken te wisselen.
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Animeer spritebewegingen met uiterlijken
