---
title: Anime o movimento do ator com fantasias
hero_image: images/banner.png
description: Anime o movimento do ator, como caminhar ou voar, alternando entre fantasias específicas
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Anime o movimento do ator com fantasias
