---
title: Anima el movimiento de los objetos con disfraces
hero_image: images/banner.png
description: Anima el movimiento de los objetos, tales como caminar o volar, cambiando entre disfraces específicos
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Anima el movimiento de los objetos con disfraces
