---
title: Animate sprite movement with costumes
hero_image: images/banner.png
description: Animate sprite movement such as walking or flying by switching between specific costumes.
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Animate sprite movement with costumes
