---
title: Animuj ruch duszków za pomocą kostiumów
hero_image: images/banner.png
description: Animuj ruchy duszków, takie jak chodzenie lub latanie, przełączając się między określonymi kostiumami
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Animuj ruch duszków za pomocą kostiumów
