---
title: Animera sprajt-rörelser med klädsel
hero_image: images/banner.png
description: Animera sprajt rörelser, som att gå eller flyga, genom att växla mellan specifika klädslar
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Animera sprajt rörelser med klädsel
