---
title: Animer le mouvement des sprites avec des costumes
hero_image: images/banner.png
description: Animer le mouvement des sprites, comme marcher ou voler, en changeant de costumes spécifiques
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Animer le mouvement des sprites avec des costumes
