---
title: Anima il movimento degli sprite con i costumi
hero_image: images/banner.png
description: Anima il movimento degli sprite, per farli camminare o volare, passando da un costume specifico all'altro
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Anima il movimento degli sprite con i costumi
